id: D13EE4C79
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:41:38+00:00'
last_modified: '2022-05-26T08:16:58.672249+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    dee7:
      image_group_id: I1PD95859
      title: དཔལ་མགོན་པོའི་གཏོར་མ།
      total_pages: 1856
      order: 14
      base_file: dee7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
