id: P6E6C3D68
initial_creation_type: ocr
source_metadata:
  volumes:
    5028aef94ed845c785e736885d5a636a:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་མགོན་པོའི་གཏོར་མ།
      total_pages: 1856
      volume_number: 14
